CREATE TABLE IF NOT EXISTS b_vit_doctor_schedule (
    ID INT AUTO_INCREMENT NOT NULL,
    DOCTOR_ID INT NOT NULL DEFAULT 0,
    WEEKDAY CHAR(3) NOT NULL,
    IS_WORKING CHAR(1) NOT NULL DEFAULT 'N',
    TIME_FROM VARCHAR(5) NOT NULL DEFAULT '09:00',
    TIME_TO VARCHAR(5) NOT NULL DEFAULT '18:00',
    PRIMARY KEY (ID),
    UNIQUE KEY UX_DOCTOR_WEEKDAY (DOCTOR_ID, WEEKDAY)
);
